### ISSUE TITLE
Issue of Jesus'Milestone

### ISSUE THREAD

**Issue by JesusGarce** [miw-upm/iwvg-git-workflow#43]
- [x] Create a new project
- [x] Give your project a name
- [ ] Press the <kbd>?</kbd> key to see available keyboard shortcuts
- [x] Add a new column
- [ ] Drag and drop this card to the new column
- [ ] Search for and add issues or PRs to your project
- [ ] Manage automation on columns
- [ ] [Archive a card]
